spring.application.name=SpringAIStarter

spring.ai.openai.api-key=${OPEN_AI_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.client-type=jedis
spring.ai.vectorstore.redis.initialize-schema=true
spring.ai.vectorstore.redis.index-name=earnings-reports
spring.ai.vectorstore.redis.prefix=earnings:

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
